### ISSUE TITLE
WADO retrieve instance giving 406

### ISSUE THREAD

**Issue by srinivasaravind5** [MGHComputationalPathology/dicomweb-client#34]
Hi, I am trying to test the wado-rs functionality for retrieve instance, the functionality works fine on postman/browser. While testing using dicomweb-client I am getting the following error.

```
http://127.0.0.1:8000 "GET /api/internal/dicomweb/ec712b95-a5fb-43bc-9de1-3ae5024e7c39/wadors/studies/2.16.124.113543.6003.1719516381.65153.16773.3015806397/series/2.16.124.113543.6003.2297816378.33047.16917.2271512738/instances/2.16.124.113543.6003.3368520785.218.17135.699537048 HTTP/1.1" 406 57
DEBUG 2020-06-30 05:03:10,741 api 77 139832964693320  request status code: 406
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<console>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/dicomweb_client/api.py", line 2084, in retrieve_instance
    return self._http_get_multipart_application_dicom(url)[0]
  File "/usr/local/lib/python3.7/site-packages/dicomweb_client/api.py", line 1045, in _http_get_multipart_application_dicom
    response = self._http_get(url, params, headers)
  File "/usr/local/lib/python3.7/site-packages/dicomweb_client/api.py", line 695, in _http_get
    response.raise_for_status()
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 406 Client Error: Not Acceptable for url: http://127.0.0.1:8000/api/internal/dicomweb/ec712b95-a5fb-43bc-9de1-3ae5024e7c39/wadors/studies/2.16.124.113543.6003.1719516381.65153.16773.3015806397/series/2.16.124.113543.6003.2297816378.33047.16917.2271512738/instances/2.16.124.113543.6003.3368520785.218.17135.699537048
```
This is how I am testing the wado retrieve instance

```
from dicomweb_client.api import DICOMwebClient
study_instance_uid = '2.16.124.113543.6003.1719516381.65153.16773.3015806397'
series_instance_uid = '2.16.124.113543.6003.2297816378.33047.16917.2271512738'
sop_instance_uid = '2.16.124.113543.6003.3368520785.218.17135.699537048'
client = DICOMwebClient(url="http://127.0.0.1:8000/api/internal/dicomweb/ec712b95-a5fb-43bc-9de1-3ae5024e7c39", wado_url_prefix="wadors")
client.retrieve_instance(study_instance_uid=study_instance_uid, series_instance_uid=series_instance_uid, sop_instance_uid=sop_instance_uid)
```
The response from the endpoint has `content_type multipart/related;type=application/dicom`. Let me know if I am doing something wrong here.

**Comment by hackermd** [comment]
@srinivasaravind5 you closed the issue. Where you able to solve it?
